export const MOCK_TASKS = [
  {
    id: 'task-1',
    title: 'Update Documentation',
    description: 'Update user guide and API documentation for v2.0 release',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignee: { id: '3', name: 'Emily Davis' },
    reporter: { id: '2', name: 'Michael Chen' },
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    tags: ['documentation', 'release'],
    progress: 60,
    workflow: [
      { status: 'CREATED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), user: 'Michael Chen' },
      { status: 'ASSIGNED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), user: 'Michael Chen' },
      { status: 'IN_PROGRESS', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), user: 'Emily Davis' },
    ],
    comments: [
      { id: '1', user: 'Michael Chen', text: 'Please prioritize the API docs', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString() },
      { id: '2', user: 'Emily Davis', text: 'Working on it, should be done by tomorrow', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString() },
    ],
  },
  {
    id: 'task-2',
    title: 'API Integration',
    description: 'Integrate payment gateway API into checkout flow',
    status: 'REVIEW',
    priority: 'URGENT',
    assignee: { id: '3', name: 'Emily Davis' },
    reporter: { id: '1', name: 'Sarah Johnson' },
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    tags: ['backend', 'payment'],
    progress: 90,
    workflow: [
      { status: 'CREATED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), user: 'Sarah Johnson' },
      { status: 'ASSIGNED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(), user: 'Sarah Johnson' },
      { status: 'IN_PROGRESS', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), user: 'Emily Davis' },
      { status: 'REVIEW', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), user: 'Emily Davis' },
    ],
    comments: [],
  },
  {
    id: 'task-3',
    title: 'Design Review',
    description: 'Review and approve new dashboard designs',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    assignee: { id: '2', name: 'Michael Chen' },
    reporter: { id: '1', name: 'Sarah Johnson' },
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    tags: ['design', 'ui'],
    progress: 100,
    workflow: [
      { status: 'CREATED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(), user: 'Sarah Johnson' },
      { status: 'ASSIGNED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(), user: 'Sarah Johnson' },
      { status: 'IN_PROGRESS', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), user: 'Michael Chen' },
      { status: 'REVIEW', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), user: 'Michael Chen' },
      { status: 'COMPLETED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), user: 'Sarah Johnson' },
    ],
    comments: [
      { id: '1', user: 'Sarah Johnson', text: 'Looks great! Approved.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
    ],
  },
  {
    id: 'task-4',
    title: 'Bug Fix #234',
    description: 'Fix pagination issue in user list',
    status: 'ASSIGNED',
    priority: 'HIGH',
    assignee: { id: '3', name: 'Emily Davis' },
    reporter: { id: '2', name: 'Michael Chen' },
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    tags: ['bug', 'frontend'],
    progress: 0,
    workflow: [
      { status: 'CREATED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), user: 'Michael Chen' },
      { status: 'ASSIGNED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(), user: 'Michael Chen' },
    ],
    comments: [],
  },
  {
    id: 'task-5',
    title: 'Database Migration',
    description: 'Migrate user data to new schema',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    assignee: { id: '2', name: 'Michael Chen' },
    reporter: { id: '1', name: 'Sarah Johnson' },
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    tags: ['database', 'migration'],
    progress: 45,
    workflow: [
      { status: 'CREATED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(), user: 'Sarah Johnson' },
      { status: 'ASSIGNED', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), user: 'Sarah Johnson' },
      { status: 'IN_PROGRESS', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), user: 'Michael Chen' },
    ],
    comments: [],
  },
];

export const MOCK_USERS_DATA = [
  { id: '1', name: 'Sarah Johnson', email: 'sarah@workflow.com', role: 'admin', status: 'active', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
  { id: '2', name: 'Michael Chen', email: 'michael@workflow.com', role: 'manager', status: 'active', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael' },
  { id: '3', name: 'Emily Davis', email: 'emily@workflow.com', role: 'employee', status: 'active', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily' },
  { id: '4', name: 'David Wilson', email: 'david@workflow.com', role: 'employee', status: 'active', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David' },
  { id: '5', name: 'Lisa Anderson', email: 'lisa@workflow.com', role: 'employee', status: 'inactive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa' },
];

export const MOCK_AUDIT_LOGS = [
  {
    id: '1',
    user: 'Sarah Johnson',
    action: 'USER_ROLE_CHANGED',
    entity: 'User',
    entityId: '5',
    before: { role: 'employee' },
    after: { role: 'manager' },
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '2',
    user: 'Michael Chen',
    action: 'TASK_CREATED',
    entity: 'Task',
    entityId: 'task-5',
    before: null,
    after: { title: 'Database Migration', status: 'CREATED' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: '3',
    user: 'Emily Davis',
    action: 'TASK_STATUS_CHANGED',
    entity: 'Task',
    entityId: 'task-2',
    before: { status: 'IN_PROGRESS' },
    after: { status: 'REVIEW' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: '4',
    user: 'Sarah Johnson',
    action: 'USER_DISABLED',
    entity: 'User',
    entityId: '5',
    before: { status: 'active' },
    after: { status: 'inactive' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const STATUS_OPTIONS = ['CREATED', 'ASSIGNED', 'IN_PROGRESS', 'REVIEW', 'COMPLETED'];
export const PRIORITY_OPTIONS = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
